### ISSUE TITLE
jsonapi has several shortcomings regarding our subclassing

### ISSUE THREAD

**Issue by mkristian** [buzzn/core#660]
the jsonapi format with subclasses has serveral short comings
```
data:
  id: e9a12807-4beb-4a31-a48f-14cddf0e51c6
  type: inputs
  links:
    self: http://localhost:3000/api/v1/register/inputs/e9a12807-4beb-4a31-a48f-14cddf0e51c6
  attributes:
    direction: in
    name: input_Jameson Hudson
    readable: friends
    uid: DE13213474163609935110731088269
    obis: 1-0:1.8.0
  relationships:
    address:
      links:
        self: http://localhost:3000/api/v1/register/inputs/e9a12807-4beb-4a31-a48f-14cddf0e51c6/relationships/address
        related: http://localhost:3000/api/v1/register/inputs/e9a12807-4beb-4a31-a48f-14cddf0e51c6/address
    meter:
      links:
        self: http://localhost:3000/api/v1/register/inputs/e9a12807-4beb-4a31-a48f-14cddf0e51c6/relationships/meter
        related: http://localhost:3000/api/v1/register/inputs/e9a12807-4beb-4a31-a48f-14cddf0e51c6/meter
    devices:
      links:
        self: http://localhost:3000/api/v1/register/inputs/e9a12807-4beb-4a31-a48f-14cddf0e51c6/relationships/devices
        related: http://localhost:3000/api/v1/register/inputs/e9a12807-4beb-4a31-a48f-14cddf0e51c6/devices
```

* type: it does not reflect our subclass and just takes the last part of the full qualified classname as type which is **not** our type. so currently the `Meter::Virtual` and `Register::Virtual` produce the same 'type' with our API endpoints
* all these **self** + **related** pairs just adds extra development load as they are two urls delivering the same content. the specification does not explain the difference.
* the jsonapi specification does allow to **include** nested resources via the **incudes** parameter - which we have not implemented. following a specification only half way can be problematic.

there are three action points here:
* fix the type in the API endpoint results
* get rid off those `related` links and use simple straight forward and intuitive links for the self. or in other words: use the link from `related` as `self` link and remove the `related` link. remove the extra endpoints which we have created here and there, dito the tests for those extra endpoints
* implement the missing features from the jsonapi
